#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                         : A Guide to Subject Indexing # The title of the book. Will be placed in the left navbar.
author                        : Doris Avedikian # The author of the book
copyright                     : "2023" # Copyright year to be placed in the footer
logo                          : logo.png # A path to the book logo
exclude_patterns              : []
#only_build_toc_files          : true

#######################################################################################
# Execution settings
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks           : "auto" # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                       : "" # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns            : [] # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                     : 100 # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp                 : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                      # otherwise the notebook's parent directory will be the cwd.
  allow_errors                : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output               : show # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# Launch button settings
launch_buttons:
  colab_url                   : "https://colab.research.google.com"
  notebook_interface          : "classic"
  binderhub_url               : "https://mybinder.org"
  thebelab                    : false  # Add a thebelab button to pages (requires the repository to run on Binder)
# Information about where the book exists on the web
repository:
  url                         : https://github.com/dorisavedikian/NALGuideToSubjectIndexing # Online location of your book
  path_to_book                : ./ # Optional path to your book, relative to the repository root
  branch                      : main # Which branch of the repository should be used when creating links (optional)
#######################################################################################
# HTML-specific settings
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                      : "fav.ico"
  baseurl                      : https://dorisavedikian.github.io/NALGuideToSubjectIndexing # The base URL where your book will be hosted.
  use_repository_button        : true
  use_issues_button            : true
  use_edit_page_button         : true
  use_download_button          : true
  extra_navbar                 : Visit our <a href="https://github.com/dorisavedikian/NALGuideToSubjectIndexingy">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>
  comments:
    hypothesis: true
  # thebe: true
  # google_analytics_id: G-XXXXXXX

#######################################################################################
# Advanced and power-user settings
sphinx:
  config:
    # html_extra_path: ["CNAME", "robots.txt"]
    html_theme_options:
      use_download_button: true
      repository_url: https://github.com/dorisavedikian/NALGuideToSubjectIndexing
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      launch_buttons:
        {
          binderhub_url: "https://mybinder.org",
          colab_url: "https://colab.research.google.com",
        }
    bibtex_reference_style: author_year

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - book/references/references.bib
  - book/references/references2.bib
  - book/references/references3.bib
  - book/references/references4.bib
  - book/references/references5.bib
  - book/references/references6.bib
  - book/references/references7.bib
  - book/references/references8.bib
  